# Spring Boot Settings
spring.application.name=BackUp_And_Restore_Model
spring.main.web-application-type=none
java.awt.headless=false

# Dongle Monitoring
rockey.monitoring.enabled=true
rockey.monitoring.interval=2

# Hardware ID Check
rockey.hardware.id.check.enabled=false